# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2a9d2af910384baa299939d922549b45bba664f6a477b5f3358ae6da021dcb831d73998cb4243e196984335f6d79190faec7a68b476337e8e17bbedae516eb6

test:
  secret_key_base: 7f7caa74dfb5c78de2c90128d76686aab6f68fc0d059b500b43e35e46f0fd7db4e05113df8bcdb4dc136d0d447623eb065dd469a2cae9d5e8b3cb6975f015ebc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
